spring:
  application:
    name: gateway-service
#  security:
#    oauth2:
#      client:
#        provider:
#          google:
#            issuer-uri: https://accounts.google.com
#        registration:
#          google:
#            client-id:
#            client-secret:
#            scope: openid,profile,email
#            redirect-uri: http://localhost:8081/login/oauth2/code/google

  zipkin:
      base-url: http://localhost:9411/
      enabled: true

  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      routes:
        - id: movie-service-route
          uri: lb://movie-service
          predicates:
            - Path=/movies/**
        - id: serie-service-route
          uri: lb://serie-service
          predicates:
            - Path=/series/**
        - id: catalog-service-route
          uri: lb://catalog-service
          predicates:
            - Path=/catalog/**

server:
  port: 8083

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    instance:
      preferIpAddress: true
